### ISSUE TITLE
IntacctException - Response result block is missing status element

### ISSUE THREAD

**Issue by ericelm** [intacct/intacct-sdk-js#70]
This is happening when `uniqueid = true` and a duplicate statistical journal entry is trying to be created.  I understand it should throw an error in this case but it seems there is a bug in the actual Result class.

```
IntacctException [Error]: Response result block is missing status element
    at new Result (/usr/src/app/node_modules/@intacct/intacct-sdk/dist/Xml/Response/Result.js:66:19)
    at new OnlineResponse (/usr/src/app/node_modules/@intacct/intacct-sdk/dist/Xml/OnlineResponse.js:55:44)
    at RequestHandler.<anonymous> (/usr/src/app/node_modules/@intacct/intacct-sdk/dist/Xml/RequestHandler.js:58:20)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/src/app/node_modules/@intacct/intacct-sdk/dist/Xml/RequestHandler.js:7:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by dylan-holt-sage** [comment]
@ericelm, just following up, please check on above comment from Jimmy.

**Comment by dylan-holt-sage** [comment]
If this issue is still occurring, please reopen the issue. Thanks.
